artifact_location: file:///c:/Users/axa/THE%20BRIDGE_23/SEMANA%2024.%20CORE.%20PROYECTO%20ML/81.%20PROYECTO%20ML/src/notebooks/mlruns/0
creation_time: 1697599024950
experiment_id: '0'
last_update_time: 1697599024950
lifecycle_stage: active
name: Default
